### ISSUE TITLE
How to introduce pagination and a bit more

### ISSUE THREAD

**Issue by LebToki** [shahroznawaz/woo-dashboard#1]
Hi there, 
would be nice to introduce pagination to all the tables and maybe pull some statistics like more sale less sale than last month and so on.
probably if we can do some chart based on the data pulled through the API would be nice.

**Comment by shahroznawaz** [comment]
Hi @LebToki Thanks for the idea, I'll find some time to work on it. Also, the PR section is open you can fork and submit the PR if you like to contribute. Otherwise I'll try to update it :)

**Comment by LebToki** [comment]
test prior to pulling my changes.
should work fine
